# Generated by Django 2.2 on 2021-04-21 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coursesapp2', '0002_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='courses_comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='coursesapp2.Course'),
        ),
    ]
