# Generated by Django 2.2 on 2021-04-22 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coursesapp2', '0003_auto_20210422_0126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='courses_comment',
            new_name='commentss',
        ),
    ]
